language: node_js
node_js:
  - 12
install:
  - make travis
script:
  - make
deploy:
  - provider: script
    script: make deploy
    skip_cleanup: true
    on:
      repo: adambkaplan/shipwright-website
      all_branches: true
